project:
  type: website

website:
  site-url: "https://meghan.quarto.pub/keeping-it-tidy/"
  title: "Keeping it Tidy"
  search: false
  favicon: logo.png
  twitter-card:
    creator: "@meghanmhall"
    image: "https://meghan.quarto.pub/keeping-it-tidy/logo.png"
  navbar:
    title: false
    logo: logo2.png
    right:
      - icon: twitter
        href: https://twitter.com/meghanmhall
      - icon: file-person-fill
        href: https://meghan.rbind.io

format:
  html:
    theme: [cosmo, theme.scss]
    css: styles.css
    toc: true
    toc-title: "Workshop Outline"

editor: visual

