project:
  type: website

website:
  title: "Keeping it Tidy"
  search: false
  navbar:
    right:
      - icon: twitter
        href: https://twitter.com/meghanmhall
      - icon: file-person-fill
        href: https://meghan.rbind.io

format:
  html:
    theme: [cosmo, theme.scss]
    css: styles.css
    toc: true
    toc-title: "Workshop Outline"

editor: visual

